In [19]:
#import numpy as np
import numpy as np 

#import pandas pd
import pandas as pd 

#create 1D array; display 
grades=np.array([78,90,98])

print(grades)

#turn above array into a Series using: pd.Series()
grades_series=pd.Series(grades)

grades_series

#create 2D array; display 

grades2=np.array([[89,92,90], [76,89,85]])

print(grades2)

#turn above 2D array into DataFrame using: pd.DataFrame()
grades2_df=pd.DataFrame(grades2)

grades2_df





[78 90 98]
[[89 92 90]
 [76 89 85]]


0   1   2
0  89  92  90
1  76  89  85

In [13]:
#create dataframe from dictionary; peers follow along 

#choices:
#temps=pd.dataframe({'Baltimore':[56, 57], 'Philly':[79,77]})
temps=pd.DataFrame({'Baltimore':[56, 57], 'Philly':[79,77]})
#temps=pd.DataFrame{'Baltimore':[56, 57], 'Philly':[79,77]}

print(temps)

#index the dataframe row with iloc and column as is 
temps.iloc[0]
temps['Baltimore']


#create custom index of years; use loc for strings and out of range integers 
temps=pd.DataFrame({'Baltimore':[56, 57], 'Philly':[79,77]}, index=[2020, 2021])

temps.iloc[0]

#change the value of Baltimore's 1st temperature to 51 with the structure: dataframe.at[row, index]= value



#choices:
#temps.at[0, 'Baltimore']=51
#temps.at(2020,'Baltimore')=51
temps.at[2020, 'Baltimore']=51




    

   Baltimore  Philly
0         56      79
1         57      77


Baltimore  Philly
2020       56.0    79.0
2021       57.0    77.0
0          51.0     NaN

In [21]:

#read a JSON file into a dataframe 

school_df=pd.read_json('matching_records.json')

print(school_df)
#add a column of 2021 with the structure: dataframe.insert(position, column name, [value 1, value 2, etc.])



#choices:
#school_df.insert(6, 2021, [1.54,1.88])
#school_df.insert(7, 2021, (1.54, 1.88))
school_df.insert(7, 2021, [1.54, 1.88])



school_df



  SchoolDistrict  2015  2016  2017  2018  2019  2020
0     Deer Lakes  0.00  0.00  0.73   0.0  0.49  0.79
1      Highlands  1.15  1.67  2.46   2.4  1.86  1.99


SchoolDistrict  2015  2016  2017  2018  2019  2020  2021
0     Deer Lakes  0.00  0.00  0.73   0.0  0.49  0.79  1.54
1      Highlands  1.15  1.67  2.46   2.4  1.86  1.99  1.88

In [8]:
#Independent activity 

#1. create dataframe any way you want(read in a json, pass a dictionary, etc. )
#2. choose at least one manipulation covered in the lesson and perform it (indexing, changing values, inserting a new column)




In [9]:
#Extension activity 
#1. create a dataframe and delete columns, and add rows, and delete them. 
#2. join 2 series into a dataframe and give it custom row labels, and custom column lables, both strings and integers
#and index them.